---
version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zookeeper:2888:3888
    volumes:
       - ./data/zookeeper/data:/data
       - ./data/zookeeper/datalog:/datalog
       - ./data/zookeeper/log/version-2/:/var/lib/zookeeper/log/version-2
       - ./data/zookeeper/data/version-2/:/var/lib/zookeeper/data/version-2
       - ./data/kafka/data/log-start-offset-checkpoint:/var/lib/kafka/data/log-start-offset-checkpoint
       - ./data/kafka/data/recovery-point-offset-checkpoint:/var/lib/kafka/data/recovery-point-offset-checkpoint
       - ./data/kafka/data/quickstart-0:/var/lib/kafka/data/quickstart-0
  broker1:
    image: confluentinc/cp-kafka
    container_name: broker1
    ports:
      - "9091:9091"
    expose:
      - 19091
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9091,PLAINTEXT_INTERNAL://broker:19091
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      #KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://broker1:19091,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9091
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1